"""Markdown renderer — the PR comment. This is the viral surface.

Designed to be readable at a glance in a GitHub PR: a clear verdict header,
one block per check with its standard mappings, and the transparent risk
breakdown so nobody has to trust a black box.
"""

from __future__ import annotations

from .. import grade as _grade
from ..checks.base import Status
from ..engine import AssuranceReport

_ICON = {Status.PASS: "\u2705", Status.REVIEW: "\u26a0\ufe0f", Status.FAIL: "\u274c"}


def _verdict_line(report: AssuranceReport) -> str:
    v = report.verdict
    if v is Status.FAIL:
        return f"{_ICON[v]} **AGENT ASSURANCE FAILED**"
    if v is Status.REVIEW:
        return f"{_ICON[v]} **AGENT ASSURANCE — REVIEW RECOMMENDED**"
    return f"{_ICON[v]} **AGENT ASSURANCE PASSED**"


def _standards_line(result) -> str:
    if not result.standards:
        return ""
    parts = []
    for s in result.standards:
        tag = f"{s.framework}:{s.control}"
        if s.relation != "maps":
            tag += f" ({s.relation})"
        parts.append(tag)
    return "Standards: " + ", ".join(parts)


def _grade_header_line(report: AssuranceReport) -> str:
    g = report.grade
    if g is None:
        return "**Grade:** n/a — no checks assessed"
    return f"**Grade:** `{g.letter}` ({g.score:g}/100) — *{g.disclaimer}*"


def _grade_breakdown(report: AssuranceReport) -> list[str]:
    """Collapsible pillar table: the grade is a summary, the pillars are the story."""
    g = report.grade
    if g is None:
        return []
    lines = ["<details><summary>Grade breakdown</summary>", ""]
    lines.append("| Pillar | Weight | Score | Basis |")
    lines.append("|---|---|---|---|")
    for p in g.pillars:
        lines.append(f"| {p.title} | {p.weight:.0%} | {p.score:g}/100 | {p.detail} |")
    lines.append("")
    if g.capped:
        ids = ", ".join(g.capped_by)
        if g.letter != g.letter_before_cap:
            lines.append(
                f"Capped at `{g.letter}`: mandatory check {ids} failed "
                f"(the pillar arithmetic alone would have been `{g.letter_before_cap}`)."
            )
        else:
            lines.append(
                f"Mandatory check {ids} failed; the grade is already at or below "
                f"the `{_grade.MANDATORY_FAIL_CAP}` cap."
            )
        lines.append("")
    lines.append(
        "_Skipped checks leave their pillar unassessed; the remaining weights are "
        "renormalised. Methodology: `docs/methodology.md`._"
    )
    lines.append("")
    lines.append("</details>")
    lines.append("")
    return lines


def to_markdown(report: AssuranceReport) -> str:
    m = report.manifest
    lines: list[str] = []
    lines.append("## \U0001f916 Agent Assurance")
    lines.append("")
    lines.append(_verdict_line(report))
    lines.append("")
    lines.append(f"**Agent:** `{m.agent.name}` v{m.agent.version}")
    fw = m.framework.name or "unknown"
    lines.append(f"**Framework:** {fw} · **Autonomy:** L{m.autonomy}")
    if report.sources:
        mode = "declared manifest verified against observed configuration" if report.declared else "observed configuration only (no manifest declared)"
        lines.append(f"**Mode:** scan — {mode}")
    if report.policy:
        lines.append(f"**Policy:** {report.policy['name']} (`{report.policy['sha256'][:12]}`)")
    lines.append(_grade_header_line(report))
    lines.append("")
    lines.extend(_grade_breakdown(report))

    for r in report.results:
        lines.append(f"### {_ICON[r.status]} {r.check_id} — {r.title} · {r.status.value}")
        lines.append("")
        lines.append(r.summary)
        lines.append("")
        for d in r.details:
            lines.append(f"- {d}")
        std = _standards_line(r)
        if std:
            lines.append("")
            lines.append(f"_{std}_")
        lines.append("")

    if report.sources:
        lines.append("<details><summary>Sources scanned</summary>")
        lines.append("")
        lines.append("| File | Kind | Status | Notes |")
        lines.append("|---|---|---|---|")
        for src in report.sources:
            status = "parsed" if src.supported else "detected, not supported"
            lines.append(f"| `{src.path}` | {src.kind} | {status} | {src.note} |")
        lines.append("")
        lines.append("</details>")
        lines.append("")

    if report.verdict is not Status.PASS:
        lines.append("---")
        lines.append("\u26a0\ufe0f **Human governance review recommended before merge.**")
        lines.append("")

    lines.append(
        "<sub>Generated by "
        "[agent-assurance](https://github.com/kunko-ai-labs/agent-assurance) · "
        "transparent, rule-based, no LLM in the scoring path.</sub>"
    )
    return "\n".join(lines)
